@@ .. @@
     // Dados de produtos simulados
     products: [
         {
             id: 1,
-            name: "Pão de Massa Azeda Artesanal",
+            name: "Pão Caseiro Tradicional",
             category: "artisan",
-            price: 425,
-            resellerPrice: 340,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Massa azeda tradicional com processo de fermentação de 24 horas, criando um sabor azedo perfeito e textura mastigável.",
-            ingredients: ["farinha orgânica", "água", "sal", "fermento de massa azeda"],
+            price: 25,
+            resellerPrice: 20,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
+            description: "Pão caseiro tradicional moçambicano, feito com farinha local e assado em fornos solares.",
+            ingredients: ["farinha de trigo", "água", "sal", "fermento", "açúcar"],
             available: true,
             stock: 12,
             dietary: ["vegetariano"],
@@ -2,17 +2,17 @@
         },
         {
             id: 2,
-            name: "Pão Integral com Sementes",
+            name: "Pão Integral Moçambicano",
             category: "whole-grain",
-            price: 362,
-            resellerPrice: 290,
-            image: "https://images.pexels.com/photos/1586947/pexels-photo-1586947.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão integral nutritivo repleto de sementes de girassol, abóbora e sésamo.",
-            ingredients: ["farinha integral", "sementes de girassol", "sementes de abóbora", "sementes de sésamo", "mel", "fermento"],
-            available: false,
-            stock: 0,
+            price: 30,
+            resellerPrice: 24,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
+            description: "Pão integral nutritivo feito com farinha local e sementes disponíveis em Moçambique.",
+            ingredients: ["farinha integral", "sementes de girassol", "gergelim", "mel local", "fermento"],
+            available: true,
+            stock: 8,
             dietary: ["vegetariano"],
             featured: false,
-            popularity: 78,
-            unavailableReason: "Falta de sementes de girassol"
+            popularity: 78
         },
         {
             id: 3,
-            name: "Baguete Francesa Clássica",
+            name: "Pão Francês Moçambicano",
             category: "artisan",
-            price: 225,
-            resellerPrice: 180,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Crosta crocante e interior macio, feito com técnicas francesas tradicionais e farinha premium.",
+            price: 15,
+            resellerPrice: 12,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
+            description: "O clássico pão francês adaptado ao gosto moçambicano, crocante por fora e macio por dentro.",
             ingredients: ["farinha de pão", "água", "sal", "fermento"],
             available: true,
             stock: 15,
             dietary: ["vegetariano", "vegano"],
             featured: true,
             popularity: 88
         },
         {
             id: 4,
-            name: "Pão Doce com Canela e Passas",
+            name: "Pão Doce Moçambicano",
             category: "sweet",
-            price: 337,
-            resellerPrice: 270,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão doce com espiral de canela e passas rechonchudas, perfeito para pequeno-almoço ou sobremesa.",
-            ingredients: ["farinha enriquecida", "passas", "canela", "açúcar", "manteiga", "ovos"],
+            price: 35,
+            resellerPrice: 28,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
+            description: "Pão doce tradicional moçambicano, perfeito para o pequeno-almoço ou lanche da tarde.",
+            ingredients: ["farinha", "açúcar", "canela", "manteiga", "ovos", "leite"],
             available: true,
             stock: 6,
             dietary: ["vegetariano"],
             featured: false,
             popularity: 82
         },
         {
             id: 5,
-            name: "Pão de Forma Sem Glúten",
+            name: "Pão de Forma Tradicional",
             category: "specialty",
-            price: 500,
-            resellerPrice: 400,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão macio e fofo sem glúten que tem o mesmo sabor do pão de trigo tradicional.",
-            ingredients: ["farinha de arroz", "fécula de tapioca", "fécula de batata", "goma xantana", "fermento"],
-            available: false,
-            stock: 0,
-            dietary: ["vegetariano", "sem glúten"],
+            price: 40,
+            resellerPrice: 32,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
+            description: "Pão de forma macio e fofo, ideal para sanduíches e torradas.",
+            ingredients: ["farinha de trigo", "leite", "açúcar", "manteiga", "fermento", "sal"],
+            available: true,
+            stock: 10,
+            dietary: ["vegetariano"],
             featured: false,
-            popularity: 65,
-            unavailableReason: "Falta de farinha de arroz"
+            popularity: 65
         },
         {
             id: 6,
-            name: "Ciabatta Rústica",
+            name: "Pão Rústico da Casa",
             category: "artisan",
-            price: 262,
-            resellerPrice: 210,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão de estilo italiano com crosta crocante e estrutura de miolo aberta e arejada.",
+            price: 20,
+            resellerPrice: 16,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
+            description: "Pão rústico artesanal com crosta crocante e miolo macio, feito com ingredientes locais.",
             ingredients: ["farinha de pão", "água", "sal", "fermento", "azeite"],
             available: true,
             stock: 10,
             dietary: ["vegetariano", "vegano"],
             featured: true,
             popularity: 75
         },
         {
             id: 7,
-            name: "Brioche com Pepitas de Chocolate",
+            name: "Pão com Chocolate",
             category: "sweet",
-            price: 412,
-            resellerPrice: 330,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Brioche rico e amanteigado salpicado com pepitas de chocolate negro premium.",
-            ingredients: ["farinha de pão", "manteiga", "ovos", "açúcar", "pepitas de chocolate negro", "fermento"],
+            price: 45,
+            resellerPrice: 36,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
+            description: "Pão doce enriquecido com chocolate, uma delícia para toda a família.",
+            ingredients: ["farinha", "manteiga", "ovos", "açúcar", "chocolate", "fermento"],
             available: true,
             stock: 5,
             dietary: ["vegetariano"],
             featured: false,
             popularity: 90
         },
         {
             id: 8,
-            name: "Pão Multicereais Power",
+            name: "Pão de Milho Tradicional",
             category: "whole-grain",
-            price: 400,
-            resellerPrice: 320,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão consistente com sete cereais diferentes para máxima nutrição e sabor.",
-            ingredients: ["farinha de trigo", "aveia", "cevada", "quinoa", "painço", "sementes de linhaça", "sementes de chia"],
-            available: false,
-            stock: 0,
+            price: 28,
+            resellerPrice: 22,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
+            description: "Pão tradicional feito com farinha de milho local, nutritivo e saboroso.",
+            ingredients: ["farinha de milho", "farinha de trigo", "água", "sal", "fermento"],
+            available: true,
+            stock: 12,
             dietary: ["vegetariano", "vegano"],
             featured: false,
-            popularity: 70,
-            unavailableReason: "Falta de quinoa"
+            popularity: 70
         },
         {
             id: 9,
-            name: "Focaccia de Alecrim",
+            name: "Pão com Ervas Locais",
             category: "artisan",
-            price: 325,
-            resellerPrice: 260,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão achatado italiano infundido com ervas com alecrim fresco e sal marinho.",
-            ingredients: ["farinha de pão", "azeite", "alecrim fresco", "sal marinho", "fermento"],
+            price: 32,
+            resellerPrice: 26,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
+            description: "Pão aromático temperado com ervas locais moçambicanas, sabor único e natural.",
+            ingredients: ["farinha de pão", "azeite", "ervas locais", "sal", "fermento"],
             available: true,
             stock: 9,
             dietary: ["vegetariano", "vegano"],
             featured: true,
             popularity: 85
         },
         {
             id: 10,
-            name: "Pão de Banana e Nozes",
+            name: "Pão de Banana Moçambicano",
             category: "sweet",
-            price: 375,
-            resellerPrice: 300,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão de banana húmido com nozes torradas e um toque de baunilha.",
-            ingredients: ["bananas", "nozes", "farinha", "açúcar", "ovos", "manteiga", "baunilha"],
+            price: 38,
+            resellerPrice: 30,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
+            description: "Pão doce feito com bananas locais maduras, húmido e saboroso.",
+            ingredients: ["bananas locais", "farinha", "açúcar", "ovos", "manteiga"],
             available: true,
             stock: 6,
             dietary: ["vegetariano"],
             featured: false,
             popularity: 80
         },
         {
             id: 11,
-            name: "Pãezinhos de Pretzel",
+            name: "Pãezinhos Tradicionais",
             category: "specialty",
-            price: 187,
-            resellerPrice: 150,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pãezinhos macios de pretzel com sal grosso, perfeitos para sanduíches ou acompanhamento.",
-            ingredients: ["farinha de pão", "fermento", "sal grosso", "bicarbonato de sódio", "manteiga"],
+            price: 12,
+            resellerPrice: 10,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
+            description: "Pãezinhos macios tradicionais, perfeitos para sanduíches ou acompanhamento.",
+            ingredients: ["farinha de pão", "fermento", "sal", "açúcar", "manteiga"],
             available: true,
             stock: 18,
             dietary: ["vegetariano"],
             featured: false,
             popularity: 72
         },
         {
             id: 12,
-            name: "Scones de Arando e Laranja",
+            name: "Biscoitos Doces da Casa",
             category: "pastries",
-            price: 212,
-            resellerPrice: 170,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Scones amanteigados com arandos secos e raspa de laranja fresca.",
-            ingredients: ["farinha", "manteiga", "arandos secos", "raspa de laranja", "açúcar", "fermento em pó"],
-            available: false,
-            stock: 0,
+            price: 18,
+            resellerPrice: 14,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
+            description: "Biscoitos doces caseiros, crocantes e saborosos, feitos com ingredientes locais.",
+            ingredients: ["farinha", "manteiga", "açúcar", "ovos", "baunilha"],
+            available: true,
+            stock: 15,
             dietary: ["vegetariano"],
             featured: false,
-            popularity: 68,
-            unavailableReason: "Falta de arandos secos"
+            popularity: 68
         },
         {
             id: 13,
-            name: "Pão de Abóbora Vegano com Especiarias",
+            name: "Pão de Abóbora Moçambicano",
             category: "specialty",
-            price: 437,
-            resellerPrice: 350,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Favorito sazonal feito com puré de abóbora e especiarias aromáticas, completamente vegano.",
-            ingredients: ["puré de abóbora", "farinha", "óleo de coco", "xarope de ácer", "canela", "noz-moscada", "cravinho"],
+            price: 42,
+            resellerPrice: 34,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
+            description: "Pão especial feito com abóbora local e especiarias tradicionais moçambicanas.",
+            ingredients: ["abóbora local", "farinha", "óleo", "açúcar", "canela", "especiarias locais"],
             available: true,
             stock: 8,
-            dietary: ["vegano", "sem lactose"],
+            dietary: ["vegetariano"],
             featured: true,
             popularity: 77
         },
         {
             id: 14,
-            name: "Pão de Aveia e Mel",
+            name: "Pão Integral com Mel",
             category: "whole-grain",
-            price: 312,
-            resellerPrice: 250,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Pão integral macio adoçado com mel natural e coberto com aveia.",
-            ingredients: ["farinha integral", "aveia", "mel", "fermento", "sal"],
+            price: 33,
+            resellerPrice: 26,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
+            description: "Pão integral macio adoçado com mel local, nutritivo e delicioso.",
+            ingredients: ["farinha integral", "mel local", "fermento", "sal", "água"],
             available: true,
             stock: 10,
             dietary: ["vegetariano"],
             featured: false,
             popularity: 75
         },
         {
             id: 15,
-            name: "Bagels Completos",
+            name: "Pães Redondos Especiais",
             category: "specialty",
-            price: 125,
-            resellerPrice: 100,
-            image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400",
-            description: "Bagels clássicos estilo Nova Iorque com mistura de temperos completos.",
-            ingredients: ["farinha de pão", "fermento", "sementes de sésamo", "sementes de papoila", "alho", "cebola", "sal"],
+            price: 22,
+            resellerPrice: 18,
+            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
+            description: "Pães redondos especiais com sementes, crocantes e saborosos.",
+            ingredients: ["farinha de pão", "fermento", "gergelim", "sal", "açúcar"],
             available: true,
             stock: 24,
             dietary: ["vegetariano", "vegano"],
             featured: false,
             popularity: 92
         }