// Dados de produtos simulados
     products: [
         {
             id: 1,
             name: "Pão Caseiro Tradicional",
             category: "artisan",
             price: 25,
             resellerPrice: 20,
             image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
             description: "Pão caseiro tradicional moçambicano, feito com farinha local e assado em fornos solares.",
             ingredients: ["farinha de trigo", "água", "sal", "fermento", "açúcar"],
             available: true,
             stock: 12,
             dietary: ["vegetariano"],
             featured: true,
             popularity: 85
        },
        {
            id: 2,
            name: "Pão Integral Moçambicano",
            category: "whole-grain",
            price: 30,
            resellerPrice: 24,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
            description: "Pão integral nutritivo feito com farinha local e sementes disponíveis em Moçambique.",
            ingredients: ["farinha integral", "sementes de girassol", "gergelim", "mel local", "fermento"],
            available: true,
            stock: 8,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 78
        },
        {
            id: 3,
            name: "Pão Francês Moçambicano",
            category: "artisan",
            price: 15,
            resellerPrice: 12,
            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
            description: "O clássico pão francês adaptado ao gosto moçambicano, crocante por fora e macio por dentro.",
            ingredients: ["farinha de pão", "água", "sal", "fermento"],
            available: true,
            stock: 15,
            dietary: ["vegetariano", "vegano"],
            featured: true,
            popularity: 88
        },
        {
            id: 4,
            name: "Pão Doce Moçambicano",
            category: "sweet",
            price: 35,
            resellerPrice: 28,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
            description: "Pão doce tradicional moçambicano, perfeito para o pequeno-almoço ou lanche da tarde.",
            ingredients: ["farinha", "açúcar", "canela", "manteiga", "ovos", "leite"],
            available: true,
            stock: 6,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 82
        },
        {
            id: 5,
            name: "Pão de Forma Tradicional",
            category: "specialty",
            price: 40,
            resellerPrice: 32,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
            description: "Pão de forma macio e fofo, ideal para sanduíches e torradas.",
            ingredients: ["farinha de trigo", "leite", "açúcar", "manteiga", "fermento", "sal"],
            available: true,
            stock: 10,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 65
        },
        {
            id: 6,
            name: "Pão Rústico da Casa",
            category: "artisan",
            price: 20,
            resellerPrice: 16,
            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
            description: "Pão rústico artesanal com crosta crocante e miolo macio, feito com ingredientes locais.",
            ingredients: ["farinha de pão", "água", "sal", "fermento", "azeite"],
            available: true,
            stock: 10,
            dietary: ["vegetariano", "vegano"],
            featured: true,
            popularity: 75
        },
        {
            id: 7,
            name: "Pão com Chocolate",
            category: "sweet",
            price: 45,
            resellerPrice: 36,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
            description: "Pão doce enriquecido com chocolate, uma delícia para toda a família.",
            ingredients: ["farinha", "manteiga", "ovos", "açúcar", "chocolate", "fermento"],
            available: true,
            stock: 5,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 90
        },
        {
            id: 8,
            name: "Pão de Milho Tradicional",
            category: "whole-grain",
            price: 28,
            resellerPrice: 22,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
            description: "Pão tradicional feito com farinha de milho local, nutritivo e saboroso.",
            ingredients: ["farinha de milho", "farinha de trigo", "água", "sal", "fermento"],
            available: true,
            stock: 12,
            dietary: ["vegetariano", "vegano"],
            featured: false,
            popularity: 70
        },
        {
            id: 9,
            name: "Pão com Ervas Locais",
            category: "artisan",
            price: 32,
            resellerPrice: 26,
            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
            description: "Pão aromático temperado com ervas locais moçambicanas, sabor único e natural.",
            ingredients: ["farinha de pão", "azeite", "ervas locais", "sal", "fermento"],
            available: true,
            stock: 9,
            dietary: ["vegetariano", "vegano"],
            featured: true,
            popularity: 85
        },
        {
            id: 10,
            name: "Pão de Banana Moçambicano",
            category: "sweet",
            price: 38,
            resellerPrice: 30,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
            description: "Pão doce feito com bananas locais maduras, húmido e saboroso.",
            ingredients: ["bananas locais", "farinha", "açúcar", "ovos", "manteiga"],
            available: true,
            stock: 6,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 80
        },
        {
            id: 11,
            name: "Pãezinhos Tradicionais",
            category: "specialty",
            price: 12,
            resellerPrice: 10,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
            description: "Pãezinhos macios tradicionais, perfeitos para sanduíches ou acompanhamento.",
            ingredients: ["farinha de pão", "fermento", "sal", "açúcar", "manteiga"],
            available: true,
            stock: 18,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 72
        },
        {
            id: 12,
            name: "Biscoitos Doces da Casa",
            category: "pastries",
            price: 18,
            resellerPrice: 14,
            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
            description: "Biscoitos doces caseiros, crocantes e saborosos, feitos com ingredientes locais.",
            ingredients: ["farinha", "manteiga", "açúcar", "ovos", "baunilha"],
            available: true,
            stock: 15,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 68
        },
        {
            id: 13,
            name: "Pão de Abóbora Moçambicano",
            category: "specialty",
            price: 42,
            resellerPrice: 34,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_41 AM.png",
            description: "Pão especial feito com abóbora local e especiarias tradicionais moçambicanas.",
            ingredients: ["abóbora local", "farinha", "óleo", "açúcar", "canela", "especiarias locais"],
            available: true,
            stock: 8,
            dietary: ["vegetariano"],
            featured: true,
            popularity: 77
        },
        {
            id: 14,
            name: "Pão Integral com Mel",
            category: "whole-grain",
            price: 33,
            resellerPrice: 26,
            image: "public/ChatGPT Image Jul 11, 2025, 02_34_20 AM.png",
            description: "Pão integral macio adoçado com mel local, nutritivo e delicioso.",
            ingredients: ["farinha integral", "mel local", "fermento", "sal", "água"],
            available: true,
            stock: 10,
            dietary: ["vegetariano"],
            featured: false,
            popularity: 75
        },
        {
            id: 15,
            name: "Pães Redondos Especiais",
            category: "specialty",
            price: 22,
            resellerPrice: 18,
            image: "public/ChatGPT Image Jul 11, 2025, 02_35_12 AM.png",
            description: "Pães redondos especiais com sementes, crocantes e saborosos.",
            ingredients: ["farinha de pão", "fermento", "gergelim", "sal", "açúcar"],
            available: true,
            stock: 24,
            dietary: ["vegetariano", "vegano"],
            featured: false,
            popularity: 92
        }
    ]